### PR TITLE
Add 'Send Settings' button

### PR DESCRIPTION
**Pull request by joro75**
Add 'Send Settings' button, to make it possible to change the settings by specifying a JSON object in the 'Description' of the 'Send Settings' button. Those settings will then be transmitted to the AWTRIX3 API when the button is pushed.

### CODE REVIEW

**Comment by galadril** [comment]
Merge conflicts

**Comment by joro75** [comment]
Merge conflict is resolved :-)

**Comment by galadril** [comment]
i didnt merge this yet because i thought you still wanted to change this in several devices?
https://github.com/galadril/Domoticz-AWTRIX3-Plugin/issues/7

**Comment by joro75** [comment]
Thanks for the merge.
The additional settings are part of another PR (See: #8), that I already prepared in the meantime, however was depending on this PR.

**Pull request merged**
